name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install verilator
      run: sudo apt-get install verilator

    - name: Install fusesoc
      run: |
        sudo pip install fusesoc
        fusesoc init -y
        
    - name: Setup project
      run: |
        cd Hardware
        fusesoc library add Illusion .
        
    - name: Simulate Command Fetcher
      run: |
        cd Hardware
        fusesoc run --target sim_command_fetcher Illusion:Illusion:Illusion:1.2

    - name: Simulate Command Processor
      run: |
        cd Hardware
        fusesoc run --target sim_command_processor Illusion:Illusion:Illusion:1.2
